$webRoot = "https://files.minecraftforge.net"
$downloadroot = "https://maven.minecraftforge.net"
$staticDir = "file://$(Get-Location)/test/static/".replace('\', '/')
python ./python/page_generator.py --webout "./test/out/" --metaout "./test/out" --config "./test/global_overrides.json" --webroot "$webRoot" --downloadroot "$downloadRoot" --static "$staticDir" --folder "./test/maven" --templates "./templates/" --local-data promote net.minecraftforge:forge 1.16.5-36.1.0 recommended
python ./python/page_generator.py --webout "./test/out/" --metaout "./test/out" --config "./test/global_overrides.json" --webroot "$webRoot" --downloadroot "$downloadRoot" --static "$staticDir" --folder "./test/maven" --templates "./templates/" --local-data promote net.minecraftforge:forge 1.16.5-36.1.2 latest
python ./python/page_generator.py --webout "./test/out/" --metaout "./test/out" --config "./test/global_overrides.json" --webroot "$webRoot" --downloadroot "$downloadRoot" --static "$staticDir" --folder "./test/maven" --templates "./templates/" --local-data promote net.minecraftforge:forge 1.18.1-39.1.0 recommended
python ./python/page_generator.py --webout "./test/out/" --metaout "./test/out" --config "./test/global_overrides.json" --webroot "$webRoot" --downloadroot "$downloadRoot" --static "$staticDir" --folder "./test/maven" --templates "./templates/" --local-data promote net.minecraftforge:forge 1.18.1-39.1.2 latest
python ./python/page_generator.py --webout "./test/out/" --metaout "./test/out" --config "./test/global_overrides.json" --webroot "$webRoot" --downloadroot "$downloadRoot" --static "$staticDir" --folder "./test/maven" --templates "./templates/" --local-data promote net.minecraftforge:forge 1.18.2-40.0.8 latest
python ./python/page_generator.py --webout "./test/out/" --metaout "./test/out" --config "./test/global_overrides.json" --webroot "$webRoot" --downloadroot "$downloadRoot" --static "$staticDir" --folder "./test/maven" --templates "./templates/" --local-data promote net.minecraftforge:froge 23w13a_or_b-april-2023.13.b.8 latest
python ./python/page_generator.py --webout "./test/out/" --metaout "./test/out" --config "./test/global_overrides.json" --webroot "$webRoot" --downloadroot "$downloadRoot" --static "$staticDir" --folder "./test/maven" --templates "./templates/" --local-data promote net.minecraftforge:froge 23w17a-2023.17.a.8 latest
python ./python/page_generator.py --webout "./test/out/" --metaout "./test/out" --config "./test/global_overrides.json" --webroot "$webRoot" --downloadroot "$downloadRoot" --static "$staticDir" --folder "./test/maven" --templates "./templates/" --local-data promote net.minecraftforge:froge 1.20.1-pre1-46.0.8 latest